objects/Appointment__c.object
<CustomObject>
    <description>Stores the details of the appointment between a physician and a patient</description>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>Stores end time of the appointment</description>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <description>Stores the patient with whom the appointment is scheduled</description>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Stores the start date and time of the appointment</description>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stores the appointment status</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PatientControllerTest.cls
/**
* @description Test Class to test PatientController
*/
@isTest
public class PatientControllerTest {
    @TestSetup
    static void prepareData(){
        
    }

    /**
    * @description Test method to test getMatchingPatients()
    */
    @isTest
    public static void testGetMatchingPatients(){
        String recTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String accId = PatientController.registerPatient('First', 'Last', System.today(), '9999999', 'test@tedst.com', recTypeId);

        System.assert(String.isNotBlank(accId));

        Test.startTest();
        list<PatientController.Patient> lstPatients = PatientController.getMatchingPatients('test@tedst.com');
        Test.stopTest();


        System.assert(lstPatients.size() == 1);
    }

    /**
    * @description Test method to test notifyPatient()
    */
    @isTest
    public static void testNotifyPatient(){
        PatientController.notifyPatient('test@tedst.com', 'test');

        String recTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String accId = PatientController.registerPatient('First', 'Last', System.today(), '9999999', 'test@tedst.com', recTypeId);

        Contact physician = new Contact();
        physician.lastName = 'Phy';

        insert physician;

        Appointment__c objApt = new Appointment__c();
        objApt.Patient__c = accId;
        objApt.Start_Time__c = System.now();
        objApt.End_Time__c = System.now();
        objApt.Status__c = 'Scheduled';
        insert objApt;

        Test.startTest();
        PatientController.notifyPatient('test@tedst.com', objApt.id);

        Test.stopTest();
        list<Contact> lstCon = [SELECT id 
                                FROM Contact
                                WHERE lastname = 'Dummy'];
        System.assert(lstCon.isEmpty());
    }
}